# 设置全局变量
[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--production=false"

# 用户端的生产环境配置
[context.production]
command = "npm run build:user"  # 用户端的构建命令
publish = "dist/user"  # 用户端的发布目录

[context.production.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com"

# 管理员端的生产环境配置
[context.admin]
command = "npm run build:admin"  # 管理员端的构建命令
publish = "dist/admin"  # 管理员端的发布目录

[context.admin.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com"

# 超级管理员端的生产环境配置
[context.superadmin]
command = "npm run build:superadmin"  # 超级管理员端的构建命令
publish = "dist/superadmin"  # 超级管理员端的发布目录

[context.superadmin.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com"
