[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--production=false"

[context.user]
command = "npm run build:user"
publish = "dist/user"

[context.user.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
