# User 端部署配置
[[build]]
base = "Frontend"
publish = "dist/user"
command = "npm run build:user"

# Admin 端部署配置
[[build]]
base = "Frontend"
publish = "dist/admin"
command = "npm run build:admin"

# Superadmin 端部署配置
[[build]]
base = "Frontend"
publish = "dist/superadmin"
command = "npm run build:superadmin"

[[redirects]]
from = "/admin/*"
to = "/admin/:splat"
status = 200

[[redirects]]
from = "/superadmin/*"
to = "/superadmin/:splat"
status = 200

[build.environment]
NODE_VERSION = "14.17.0"
