[build]
base = "CrazyThursday-clean/Frontend"   # 设置为前端代码的正确路径
publish = "dist"                       # Vite 构建输出的文件夹
command = "npm run build:user"         # 确保这个命令在 package.json 中定义

[build.environment]
NODE_VERSION = "14.17.0"
