# 配置 user 端
[build]
publish = "dist" # user 端发布的目录
command = "npm run build:user" # user 端的构建命令

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com/api"

# 配置 admin（doctor）端
[context.admin]
publish = "dist/admin" # admin 端发布的目录
command = "npm run build:admin" # admin 端的构建命令

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.admin.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com/api"

# 配置 superadmin 端
[context.superadmin]
publish = "dist/superadmin" # superadmin 端发布的目录
command = "npm run build:superadmin" # superadmin 端的构建命令

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.superadmin.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com/api"
