[build]
base = "Frontend"
command = "npm run build:all"
publish = "dist"

[build.environment]
NODE_VERSION = "14.17.0"

[[redirects]]
from = "/admin/*"
to = "/admin/:splat"
status = 200

[[redirects]]
from = "/superadmin/*"
to = "/superadmin/:splat"
status = 200
