# 通用配置
[build]
command = "npm ci && npm run build:all"  # 同时构建 user, admin 和 superadmin
publish = "dist"  # 默认发布目录

[build.environment]
NODE_VERSION = "14.17.0"

# 通用重定向规则
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# user 端的生产环境配置
[context.production]
command = "npm run build:user"  # user 端的构建命令
publish = "dist"  # user 端的发布目录

[context.production.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com/api"

# admin 端的生产环境配置
[context.admin]
command = "npm run build:admin"  # admin 端的构建命令
publish = "dist/admin"  # admin 端的发布目录

[context.admin.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com/api"

# superadmin 端的生产环境配置
[context.superadmin]
command = "npm run build:superadmin"  # superadmin 端的构建命令
publish = "dist/superadmin"  # superadmin 端的发布目录

[context.superadmin.environment]
NODE_ENV = "production"
REACT_APP_API_URL = "https://curachatbot.herokuapp.com/api"
